; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Global settings for the entire project
default_envs = clangtidy
name = My Feather M0 Project
description = A PlatformIO project for the Adafruit Feather M0 board

[env:clangtidy]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
monitor_speed = 115200

test_framework = unity
; Disable building src/ for unit tests
test_build_src = yes

; Only run tests in the unit/ folder
test_filter = unit/*

build_flags =
  -D__PIO_BOARD_NAME__=\"${this.board}\"
  -DLOG_LEVEL=LOG_LEVEL_DEBUG
  -DLOG_SERIAL_LEVEL=LOG_LEVEL_DEBUG
  -DLOG_SERIAL_OUTPUT=LOG_SERIAL1
  ; Include directories
  ; see c_cpp_properties.json
    -I include/app/
    -I include/core/
    -I include/drivers/
    -I include/hal/
    -I src/app/
    -I src/core/
    -I src/drivers/
    -I src/hal/

  ; Linker GC
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections

  -Wno-system-headers
  -Wno-pedantic
  -Wno-address-of-packed-member

; build_src_flags =
  ; -Wall
  ; -Wextra
  ; -Wpedantic
  ; -Wshadow
  ; -Wsign-conversion
  ; -Wduplicated-cond
  ; -Wduplicated-branches
  ; -Wnull-dereference
  ; -Wconversion
  ; -Wswitch-enum
  ; -Wmissing-declarations
  ; -Wuseless-cast
  ; Arduino / libs noise control
  -Wno-system-headers
  -Wno-address-of-packed-member

; Static analysis (clang-tidy) via PlatformIO: run with `pio check`
check_tool = clangtidy
check_flags =
  clangtidy: --config-file=.clang-tidy

lib_deps =
	ocrdu/SAMD21 turbo PWM@^0.8.5
	adafruit/RTClib@^2.1.4
  arduino-libraries/Arduino Low Power@^1.2.2
	bblanchon/ArduinoJson@^6.21.5
	adafruit/Adafruit MAX31865 library@^1.3.0
	drhaney/pt100rtd library@^0.1
	arduino-libraries/SD@^1.3.0
	cmaglie/FlashStorage@^1.0.0
  adafruit/Adafruit SleepyDog Library@^1.8.4


extra_scripts =
  ; pre:scripts/gen_compdb.py
  post:scripts/convert_to_uf2.py
  ; post:scripts/post_filter_warnings.py

[env:cppcheck]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
monitor_speed = 115200

test_framework = unity
; Disable building src/ for unit tests
test_build_src = yes

; Only run tests in the unit/ folder
test_filter = unit/*

build_flags =
  -D__PIO_BOARD_NAME__=\"${this.board}\"
  -DLOG_LEVEL=LOG_LEVEL_DEBUG
  -DLOG_SERIAL_LEVEL=LOG_LEVEL_DEBUG
  -DLOG_SERIAL_OUTPUT=LOG_SERIAL1
  ; Include directories
  ; see c_cpp_properties.json
    -I include/app/
    -I include/core/
    -I include/drivers/
    -I include/hal/
    -I src/app/
    -I src/core/
    -I src/drivers/
    -I src/hal/

  ; Linker GC
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections

  ; Warnings project
  -Wall
  -Wextra
  -Wduplicated-cond
  -Wduplicated-branches
  -Wnull-dereference
  -Wconversion

  ; Arduino / libs noise control
  -Wno-system-headers
  -Wno-address-of-packed-member

; Static analysis (clang-tidy) via PlatformIO: run with `pio check`
check_tool = cppcheck
check_skip_packages = yes
check_flags =
  cppcheck:
    --enable=warning,performance,portability
    --inconclusive
    --std=c++17
    --suppress=missingIncludeSystem
    --suppress=unusedFunction

    --suppress=uninitMemberVar:.pio\libdeps\cppcheck\*
    --suppress=duplInheritedMember:.pio\libdeps\cppcheck\*
    --suppress=passedByValue:.pio\libdeps\cppcheck\*
    --suppress=legacyUninitvar:.pio\libdeps\cppcheck\*

    --suppress=uninitMemberVar:.pio/libdeps/cppcheck/*
    --suppress=duplInheritedMember:.pio/libdeps/cppcheck/*
    --suppress=passedByValue:.pio/libdeps/cppcheck/*
    --suppress=legacyUninitvar:.pio/libdeps/cppcheck/*

    -i.pio
    -i.vscode
    -i.git
    -i.platformio
    --verbose
    --max-configs=10
    src
    include


lib_deps =
	ocrdu/SAMD21 turbo PWM@^0.8.5
	adafruit/RTClib@^2.1.4
  arduino-libraries/Arduino Low Power@^1.2.2
	bblanchon/ArduinoJson@^6.21.5
	adafruit/Adafruit MAX31865 library@^1.3.0
	drhaney/pt100rtd library@^0.1
	arduino-libraries/SD@^1.3.0
	cmaglie/FlashStorage@^1.0.0
