; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
lib_deps =
	ocrdu/SAMD21 turbo PWM@^0.8.5
	adafruit/RTClib@^2.0.2
	bblanchon/ArduinoJson@^6.19.4
	adafruit/Adafruit MAX31865 library@^1.3.0
	drhaney/pt100rtd library@^0.1
	arduino-libraries/SD@^1.2.4
	cmaglie/FlashStorage @ ^1.0.0